server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: CooksCorner

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: 3167ceee9cb36d05a553fd48752e077e8e2c7edef0c046f7bc7a38678f7bd8da
